
export const I18N = {
  zh: {
    authT: "师傅登录",
    authS: "还没有账号？点击注册",
    authB: "进入系统",
    regT: "师傅注册",
    regS: "已有账号？点击登录",
    regB: "完成注册并登录",
    welcome: "，您好！",
    logout: "退出",
    proj: "项目管理",
    ledger: "账目报表",
    exp: "今日支出总计",
    note: "材料记事本",
    memo: "备料计划/便签",
    sec: "AI 小秘书为您服务中",
    back: "返回主页",
    save: "确认保存",
    hst: "安省 HST 13% 税务计算",
    voiceT: "正在倾听您的指令...",
    cancel: "取消操作",
    pending: "暂无照片",
    add: "新增记录",
    siteName: "工地名称",
    ownerPhone: "联系电话",
    amount: "金额 ($)",
    usage: "支出用途",
    loadingAI: "AI 正在思考...",
    photoLoaded: "照片读取成功",
    password: "登录密码",
    clearData: "重置",
    clearConfirm: "确定要清空所有数据吗？此操作不可撤销。",
    clearFinal: "再次确认：所有账目和项目都将被删除！"
  },
  en: {
    authT: "Master Login",
    authS: "No account? Register here",
    authB: "Login to System",
    regT: "Registration",
    regS: "Already have account? Login",
    regB: "Sign Up & Enter",
    welcome: ", Welcome back!",
    logout: "Logout",
    proj: "Project Management",
    ledger: "Financial Ledger",
    exp: "Total Daily Expenses",
    note: "Materials Notebook",
    memo: "Planning / Sticky Notes",
    sec: "AI Assistant Active",
    back: "Go Back",
    save: "Save Entry",
    hst: "Ontario HST 13% Split",
    voiceT: "Listening to your command...",
    cancel: "Cancel",
    pending: "No Photo",
    add: "Add New",
    siteName: "Site Name",
    ownerPhone: "Owner Phone",
    amount: "Amount ($)",
    usage: "Usage/Description",
    loadingAI: "AI is thinking...",
    photoLoaded: "Photo Loaded",
    password: "Password",
    clearData: "Reset",
    clearConfirm: "Are you sure you want to clear ALL data? This cannot be undone.",
    clearFinal: "FINAL WARNING: All ledger and projects will be permanently deleted!"
  }
};
